import path from 'node:path';

import type {FileInfo} from 'jscodeshift';
import postcss, {Plugin} from 'postcss';

const plugin = (): Plugin => {
  const commentContext = 'generated by polaris-migrator';
  const disableNextLine = 'stylelint-disable-next-line';
  const polarisDisableComment = `${disableNextLine} -- polaris: ${commentContext}`;

  return {
    postcssPlugin: 'insert-stylelint-disable',
    Once(_, {result}) {
      result.messages.forEach((warning) => {
        // Don't insert ignore comments for non stylelint polaris warnings
        if (!warning.rule.startsWith('stylelint-polaris')) {
          return;
        }

        const beforeWarningText = warning.node.prev()?.text;

        // Don't insert another ignore comment if one was already added by the plugin
        if (beforeWarningText?.includes(polarisDisableComment)) {
          return;
        }

        // If a nextline comment already exists above the warning node,
        // combine the rules and descriptions into a single disable comment.
        let existingText = '';

        if (beforeWarningText?.includes(disableNextLine)) {
          const description = beforeWarningText.split(
            `${disableNextLine} `,
          )?.[1];

          if (description.length) {
            existingText = `, ${description}`;
          }

          warning.node.prev().remove();
        }

        // Create a new comment node and insert above the warning node
        const comment = new postcss.Comment({
          text: `${polarisDisableComment}${existingText}`,
          raws: {
            left: ' ',
            right: '',
            inline: true,
          },
        });

        warning.node.before(comment);

        // Ensure there is only one new line character between the
        // disable next line comment and the warning node
        warning.node.raws.before = `\n${warning.node.raws.before.replace(
          /\n/g,
          '',
        )}`;
      });
    },
  };
};

export default async function insertStylelintDisable(file: FileInfo) {
  return postcss([
    require('stylelint')({
      configFile: path.resolve(__dirname, './stylelint.config.js'),
    }),
    plugin(),
  ])
    .process(file.source, {
      from: file.path,
      syntax: require('postcss-scss'),
    })
    .then((result) => {
      return result.css;
    });
}
